### ISSUE TITLE
Comment section on Editing Droid screen

### ISSUE THREAD

**Issue by ridilen** [Droid-Builder-Web-Team/ChecklistApp#161]
Would be nice to have a comments section available.  I have custom upper ring, open back panel and other items.  Would be nice to log differences from the parts lists available.

![image](https://user-images.githubusercontent.com/57424927/96056587-fecfb900-0e54-11eb-971c-1beb4593fdba.png)

**Comment by RobHowdle** [comment]
A comments section is something on the list of future additions however customisation of parts away from what Michael has released (unless Michael has released them/ added them to his onedrive) is not something we would support and be able to cater for since there is a truely unlimited amount of ways they can be customised we simply couldn't cater for everything.

**Comment by RobHowdle** [comment]
Notes section added to it's own separate tab.
